CMR2_RALLY_NAMES = [
    "Finland",
    "Greece",
    "France",
    "Sweden",
    "Australia",
    "Kenya",
    "Italy",
    "United Kingdom"
]

CMR2_SPECIAL_STAGES = [13, 27, 41, 55]

CMR2_ARCADE_RALLIES = [
    "Italy",
    "Sweden",
    "Greece",
    "Australia",
    "Finland",
    "France",
    "Kenya",
    "United Kingdom"
]

CMR2_STAGE_NAMES = [
    "Mikkeli",
    "Kupio",
    "Joensuu",
    "Mikkeli (R)",
    "Kemijärvi",
    "Rovaniemi",
    "Kittilä",
    "Kemijärvi (R)",
    "Jamsa",
    "Tampere",
    "",
    "Kivotos",
    "Kalabaka",
    "Dodona",
    "Kilkis",
    "Smolikas",
    "Grammos",
    "Siatista",
    "Kozani",
    "Kilkis (R)",
    "Kozani (R)",
    "Super-Special",
    "Ballon",
    "Authon",
    "Livarot",
    "Falaise",
    "Falaise (R)",
    "Livarot (R)",
    "Dreux",
    "Damville",
    "Vhauny",
    "Laon",
    "",
    "Mora",
    "Hoting",
    "Bispfors",
    "Ange",
    "Karlstad",
    "Arvika",
    "Falun",
    "Mora (R)",
    "Tranas",
    "Skara",
    "Super-Special",
    "Wongawol",
    "Earaheady",
    "Wiluna",
    "Elendale",
    "Billuna",
    "Mornington",
    "Elendale (R)",
    "Billuna (R)",
    "Warrie",
    "Kooline",
    "",
    "Lokichar",
    "Kapuitr",
    "Kalossia",
    "Lokichar (R)",
    "Buna",
    "Holta",
    "Choba",
    "Buna (R)",
    "Lodwar",
    "Pelekech",
    "Super-Special",
    "Modena",
    "Carpi",
    "Vignola",
    "Lodi",
    "Castel",
    "Voghera",
    "Lodi (R)",
    "Valenza",
    "Celano",
    "Rieti",
    "",
    "Richmond",
    "Dalton",
    "Melsonby",
    "Richmond (R)",
    "Darton",
    "Ripley",
    "Darton (R)",
    "Ripley (R)",
    "Caersw",
    "Penybont",
    "Super-Special"
]

CMR2_CAR_NAMES = {
    0b01010 : "Peugeot 206",
    0b00100 : "Mitsubishi Lancer",
    0b00000 : "Ford Focus",
    0b01001 : "Subaru Impreza",
    0b01000 : "Toyota Corolla",
    0b00111 : "Mitsubishi Lancer Road Car",
    0b01011 : "SEAT Cordoba",
    0b10000 : "Mini Cooper S",
    0b01111 : "Ford Sierra Cosworth"
}

DIFFICULTIES = [
    "Novice",
    "Intermediate",
    "Expert"
]