CMR_RALLY_NAMES = [
    "New Zealand",
    "Greece",
    "Monte Carlo",
    "Australia",
    "Sweden",
    "Corsica",
    "Indonesia",
    "Great Britain"
]

CMR_SPECIAL_STAGES = [13, 27, 41, 55]

CMR_STAGE_NAMES = [
    "NZ 1",
    "NZ 2",
    "NZ 3",
    "NZ 4",
    "NZ 5",
    "NZ 6",
    "",
    "GR 1",
    "GR 2",
    "GR 3",
    "GR 4",
    "GR 5",
    "GR 6",
    "GR SS",
    "MC 1",
    "MC 2",
    "MC 3",
    "MC 4",
    "MC 5",
    "MC 6",
    "",
    "AU 1",
    "AU 2",
    "AU 3",
    "AU 4",
    "AU 5",
    "AU 6",
    "AU SS",
    "SE 1",
    "SE 2",
    "SE 3",
    "SE 4",
    "SE 5",
    "SE 6",
    "",
    "CO 1",
    "CO 2",
    "CO 3",
    "CO 4",
    "CO 5",
    "CO 6",
    "CO SS",
    "IN 1",
    "IN 2",
    "IN 3",
    "IN 4",
    "IN 5",
    "IN 6",
    "",
    "GB 1",
    "GB 2",
    "GB 3",
    "GB 4",
    "GB 5",
    "GB 6",
    "GB SS",
]

CMR_CAR_NAMES = {
    5: 'Ford Escort MK II',
    6: 'Mitsubishi Lancer E4',
    0: 'Subaru Impreza WRC',
    10: 'Ford Escort WRC',
    9: 'Toyota Corolla WRC',
    11: 'Renault Maxi Megane',
    7: 'VW Golf GTI Kit Car',
    2: 'Skoda Felicia Kit Car',
    1: 'Seat Ibiza Kit Car EVO2'
}