CMR_RALLY_NAMES = [
    "New Zealand",
    "Greece",
    "Monte Carlo",
    "Australia",
    "Sweden",
    "Corsica",
    "Indonesia",
    "Great Britain"
]

CMR_SPECIAL_STAGES = [13, 27, 41, 55]

CMR_STAGE_NAMES = [
    "Wellsford",
    "Okahu",
    "Makaru",
    "Glenbrook",
    "Thames",
    "Waihl",
    "",
    "Stanos",
    "Stagira",
    "Embesos",
    "Kariani",
    "Auli",
    "Krinides",
    "Super-Special",
    "Charols",
    "Pradelle",
    "Serres",
    "Sisteron",
    "Riez",
    "Broues",
    "",
    "Broomehill",
    "Corrigin",
    "Donnybrook",
    "Wongan Hills",
    "Bluff Knoll",
    "Moora",
    "Super-Special",
    "Filipstad",
    "Lilijendal",
    "Vansbro",
    "Borlange",
    "Ludvik",
    "Rockesholm",
    "",
    "Nonza",
    "Luri",
    "Campitello",
    "Sermano",
    "Euisa",
    "Ajaccio",
    "Super-Special",
    "Gebang",
    "Bohorok",
    "Prapat",
    "Porsea",
    "Sukajadi",
    "Tanjungbalai",
    "",
    "New Castleton",
    "Kielder Waters",
    "Barningham",
    "Greenhow Hill",
    "F. of Bowland",
    "Dolgellau",
    "Super-Special",
]

CMR_CAR_NAMES = {
    5: 'Ford Escort MK II',
    6: 'Mitsubishi Lancer E4',
    0: 'Subaru Impreza WRC',
    10: 'Ford Escort WRC',
    9: 'Toyota Corolla WRC',
    11: 'Renault Maxi Megane',
    7: 'VW Golf GTI Kit Car',
    2: 'Skoda Felicia Kit Car',
    1: 'Seat Ibiza Kit Car EVO2',
    4: 'Ford RS200',
    8: 'Lancia Delta Integrale',
    3: 'Audi Quattro',
    12: "Millenium 4 Rallye",
    13: "Toyota Celica GT4 WRC"
}